version: '3.8'

services:
  front-end:
    build: ./front-end
    container_name: safe-speech-front-end
    hostname: front-end
    ports:
      - '8080:8080'

  back-end:
    build: ./back-end
    container_name: safe-speech-back-end
    hostname: back-end
    ports:
      - '8000:8000'