version: "3.8"

services:
  front-end:
    build: ./front-end
    container_name: safe-speech-front-end
    hostname: front-end
    environment:
      - VUE_APP_BACK_END_URL=http://safespeech.onthewifi.com:8000
    ports:
      - "80:8080"

  back-end:
    build: ./back-end
    # image: test:latest
    container_name: safe-speech-back-end
    hostname: back-end
    ports:
      - "8000:8000"
